# Generated by Django 5.2.13 on 2026-04-10 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=15)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("default_address", models.TextField(blank=True, default="")),
                (
                    "default_city",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "default_pincode",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("tea_tokens", models.PositiveIntegerField(default=0)),
                (
                    "loyalty_tier",
                    models.CharField(
                        choices=[
                            ("pehla_cup", "Pehla Cup"),
                            ("chai_premi", "Chai Premi"),
                            ("masala_raja", "Masala Raja"),
                            ("shahi_mehman", "Shahi Mehman"),
                        ],
                        default="pehla_cup",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
