# Generated by Django 5.1.6 on 2026-04-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("memberships", "0003_membershiptier_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="active_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="memberships.membershiptier",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="loyalty_tier",
            field=models.CharField(
                choices=[
                    ("naya_patron", "Naya Patron"),
                    ("brass_baron", "Brass Baron"),
                    ("heritage_keeper", "Heritage Keeper"),
                    ("maharaja", "Maharaja"),
                ],
                default="naya_patron",
                max_length=20,
            ),
        ),
    ]
