# Generated by Django 5.1.6 on 2026-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SommelierCuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("features", models.JSONField(default=list)),
                ("icon", models.CharField(default="workspace_premium", max_length=50)),
                ("badge_text", models.CharField(blank=True, default="", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.DeleteModel(
            name="SubscriptionPlan",
        ),
    ]
