# Generated by Django 5.1.6 on 2026-04-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_sommeliercuration_delete_subscriptionplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
