# Generated by Django 5.1.6 on 2026-04-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="gifthamper",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="sommeliercuration",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
