# Generated by Django 5.1.6 on 2026-04-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_gifthamper_stock_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sommeliercuration",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="curations/"),
        ),
        migrations.AddField(
            model_name="sommeliercuration",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
