# Generated by Django 5.1.6 on 2026-04-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("upi", "Digital UPI Vault"),
                    ("card", "Credit/Debit Card"),
                    ("bank", "Traditional Banking"),
                    ("netbanking", "Traditional Banking"),
                    ("cod", "Cash on Arrival"),
                ],
                max_length=20,
            ),
        ),
    ]
