# Generated by Django 5.1.6 on 2026-04-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("memberships", "0004_membershiptier_feature_keys"),
        ("orders", "0002_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="membership_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="memberships.membershiptier",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.product",
            ),
        ),
    ]
