# Generated by Django 5.1.6 on 2026-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_usermembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptier",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name="UserMembership",
        ),
    ]
