# Generated by Django 5.1.6 on 2026-04-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0003_membershiptier_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptier",
            name="feature_keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
