# Generated by Django 5.2.13 on 2026-04-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("history", "History"),
                            ("recipe", "Recipe"),
                            ("culture", "Culture"),
                            ("origin", "Origin Story"),
                            ("guide", "Guide"),
                        ],
                        default="history",
                        max_length=20,
                    ),
                ),
                ("excerpt", models.TextField()),
                ("body", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                ("cover_image_url", models.URLField(blank=True, default="")),
                (
                    "author_name",
                    models.CharField(
                        default="Heritage Brews Editorial", max_length=100
                    ),
                ),
                ("read_time", models.PositiveIntegerField(default=5)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="estates/"),
                ),
                ("image_url", models.URLField(blank=True, default="")),
                ("altitude", models.CharField(blank=True, default="", max_length=50)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("map_latitude", models.FloatField(blank=True, null=True)),
                ("map_longitude", models.FloatField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="farmers/"),
                ),
                ("photo_url", models.URLField(blank=True, default="")),
                ("generation", models.CharField(blank=True, default="", max_length=50)),
                ("quote", models.TextField(blank=True, default="")),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmers",
                        to="content.estate",
                    ),
                ),
            ],
        ),
    ]
