# Generated by Django 5.2.13 on 2026-04-10 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patron_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("table", "Standard Table Reservation"),
                            ("partial", "Exclusive Sanctuary (Hourly Private Booking)"),
                            ("full", "The Grand Buyout (Full Day Haveli Reservation)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("time_or_duration", models.CharField(max_length=100)),
                (
                    "guests",
                    models.CharField(
                        choices=[
                            ("1-2", "1–2 Connoisseurs"),
                            ("3-5", "3–5 Patrons"),
                            ("6-10", "6–10 Patrons"),
                            ("10-25", "10–25 (Private Gathering)"),
                            ("25+", "25+ (Grand Celebration)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("casual", "Casual Visit / High Tea"),
                            ("birthday", "Birthday Celebration"),
                            ("anniversary", "Anniversary / Engagement"),
                            ("business", "Corporate Meeting / Offsite"),
                            ("wedding", "Pre-Wedding / Shagun Ceremony"),
                            ("other", "Other Cultural Gathering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("special_instructions", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "confirmation_code",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
