# Generated by Django 5.2.13 on 2026-04-10 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("min_tokens", models.PositiveIntegerField()),
                ("max_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("icon", models.CharField(default="filter_vintage", max_length=50)),
                ("color", models.CharField(default="#cd7f32", max_length=7)),
                ("description", models.TextField(blank=True, default="")),
                ("perks", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["min_tokens"],
            },
        ),
        migrations.CreateModel(
            name="TokenTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earned"),
                            ("redeem", "Redeemed"),
                            ("bonus", "Bonus"),
                            ("expire", "Expired"),
                        ],
                        default="earn",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="token_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
